[phases.setup]
nixPkgs = ['php', 'phpPackages.composer', 'nodejs_20']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'npm install'
]

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'